version: "3"

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    image: chainlog-ui
    container_name: chainlog-ui
    environment:
      CHECKSUM_CONTAINER_NAME: checksum
    networks:
      - chainlog-ui-network
    ports:
      - "0.0.0.0:8080:80/tcp"
    volumes:
      - ./api:/usr/share/nginx/html/api
  logger:
    build:
      context: .
      dockerfile: Dockerfile.logger
    image: chainlog-logger
    container_name: chainlog-logger
    environment:
      INFURA_KEY: $INFURA_KEY
      GITHUB_TOKEN: $GITHUB_TOKEN
      CHAINLOG_REPO: "gsu-protocol/chainlog-ui"
      PYTHONUNBUFFERED: 1
    networks:
      - chainlog-ui-network
    volumes:
      - ./api:/usr/app/src/api
  checksum:
    build:
      context: .
      dockerfile: Dockerfile.checksum
    image: chainlog-checksum
    container_name: chainlog-checksum
    networks:
      - chainlog-ui-network

networks:
  chainlog-ui-network:
    name: chainlog-ui-network
    driver: bridge
